glitches:
        gspy_file: "/home/andre.guimaraes/public_html/gstlal/offline_analysis/GstLALGspy/Large_Volume_Analysis/data/glitch/O3glitches.csv" 
        omic_file: "/home/andre.guimaraes/public_html/gstlal/offline_analysis/GstLALGspy/Large_Volume_Analysis/data/glitch/omicron.csv"

triggers:
        pipeline: "gstlal"
        clean-trigger-file: "/home/andre.guimaraes/public_html/gstlal/offline_analysis/GstLALGspy/Large_Volume_Analysis/data/CleanTriggerFiles"
        dirty-trigger-file: "/home/andre.guimaraes/public_html/gstlal/offline_analysis/GstLALGspy/Large_Volume_Analysis/data/DirtyTriggerFiles"
        other-trigger-file: "/home/andre.guimaraes/public_html/gstlal/offline_analysis/GstLALGspy/Large_Volume_Analysis/data/OtherTriggerFiles"
plots:
        plots-dir: "./plots"

worklow:
        omicron-snr-cutoff: 6
        percentile-cutoff: 99
        machine-learning-cut: False
        machine-learning-cat: False
        temp-dir: "./temp"
        tag: gstlal_01
