glitches:
        gspy-file: "/home/andre.guimaraes/public_html/gstlal/offline_analysis/GstLALGspy/Large_Volume_Analysis/data/glitch/O3glitches.csv" 
        omic-file: "/home/andre.guimaraes/public_html/gstlal/offline_analysis/GstLALGspy/Large_Volume_Analysis/data/glitch/omicron.csv"

triggers:
        pipeline: "gstlal"
        raw-trigger-dir: "/home/andre.guimaraes/public_html/gstlal/offline_analysis/GstLALGspy/Large_Volume_Analysis/data/gstlal/TriggerFiles"
        clean-trigger-dir: "/home/andre.guimaraes/public_html/gstlal/offline_analysis/GstLALGspy/Large_Volume_Analysis/data/gstlal/CleanTriggerFiles"
        dirty-trigger-dir: "/home/andre.guimaraes/public_html/gstlal/offline_analysis/GstLALGspy/Large_Volume_Analysis/data/gstlal/DirtyTriggerFiles"
        other-trigger-dir: "/home/andre.guimaraes/public_html/gstlal/offline_analysis/GstLALGspy/Large_Volume_Analysis/data/gstlal/OtherTriggerFiles"
plots:
        plots-dir: "./plots"


workflow:
        trigger-finding:
                omicron-snr-cutoff: 6
        cutoff:
                number-bins: 200
                cutoff-params: ['log_snr', 'log_chisqBysnrsq', 'log_bankchisqBysnrsq']
                percentile-cutoff: 99
                machine-learning-cutoff: True
                machine-learning-samples: 100000
        categorization:
                machine-learning-cat: False
        other:
                temp-dir: "./temp"
                log-dir: "./logs"
                log: True
                tag: "gstlal_01"
